version: 1
from: "infracamp/kickstart-flavor-gaia:testing"

apache_fallback_resource: "/index.php"

command:
  build:
    - "sudo apt-get update && sudo apt-get install -y letsencrypt"
    - "composer update"

  test:
    - "vendor/bin/phpunit tests/"
